Fix for this error:
ERROR: While executing gem ... (TypeError)
      ./watir.rb:1286:in `+´: can´t convert nil into String

I assume that this happened because the gem was built from an export instead of a checkout.