Fix for intermittent crashes occuring when using Watir with Ruby version > 1.8.2. Fix for http://jira.openqa.org/browse/WTR-86 This fix prevents the Watir-modified win32ole.so library (compiled against 1.8.2) from being used.
Consequently, IE#modal_dialog will not work (as before) with Ruby version > 1.8.2.
However, when this is attempted, this is the new error message:

  NoMethodError: IE#modal_dialog not supported with the current version of Ruby (1.8.4).
  See http://jira.openqa.org/browse/WTR-2 for details.
  undefined method `connect_unknown' for WIN32OLE:Class